# fly.toml file generated for bme-sensors-logging on 2023-01-16T17:26:30+08:00

app = "bme-sensors-logging"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  image = "victoriametrics/victoria-metrics"

[mounts]
  source="vicky_data"
  destination="/victoria-metrics-data"

[experimental]
  auto_rollback = true
  cmd = ["--graphiteListenAddr=:2003"]

[[services]]
  internal_port = 8428
  protocol = "tcp"

  [[services.ports]]
    port = 8428

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 2003
  protocol = "tcp"

  [[services.ports]]
    port = 2003

[[services]]
  internal_port = 2003
  protocol = "udp"

  [[services.ports]]
    port = 2003
