on: [push]

name: CI Build

jobs:
  build_and_test:
    name: Rust project
    runs-on: ARM64
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target armv7-unknown-linux-gnueabihf
